"use client";

import { useEffect, useState } from "react";
import { BellRing, CalendarClock, Megaphone, Send, X } from "lucide-react";

type Announcement = { id: string; title: string; message: string; audience: string; startsAt: string; endsAt: string | null; active: boolean; sender: string; chain: string | null; analyst: string | null };
type Option = { id: string; nombre: string; role?: string; activo?: boolean };
const emptyForm = () => ({ title: "", message: "", audience: "TODOS", chainId: "", analystId: "", startsAt: new Date().toISOString().slice(0, 16), endsAt: "" });

export function AnnouncementsCenter({ admin, onClose }: { admin: boolean; onClose: () => void }) {
  const [items, setItems] = useState<Announcement[]>([]);
  const [chains, setChains] = useState<Option[]>([]);
  const [users, setUsers] = useState<Option[]>([]);
  const [tab, setTab] = useState<"current" | "create">("current");
  const [form, setForm] = useState(emptyForm);
  const [saving, setSaving] = useState(false);
  const [notice, setNotice] = useState("");

  async function load() { const data = await fetch("/api/announcements").then((response) => response.json()); if (Array.isArray(data)) setItems(data); }
  useEffect(() => { fetch("/api/announcements").then((response) => response.json()).then((data) => { if (Array.isArray(data)) setItems(data); }); if (admin) Promise.all([fetch("/api/chains").then((response) => response.json()), fetch("/api/users").then((response) => response.json())]).then(([chainData, userData]) => { if (Array.isArray(chainData)) setChains(chainData); if (Array.isArray(userData)) setUsers(userData); }); }, [admin]);
  async function publish() { setSaving(true); setNotice(""); const response = await fetch("/api/announcements", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, chainId: form.chainId || null, analystId: form.analystId || null, startsAt: new Date(form.startsAt).toISOString(), endsAt: form.endsAt ? new Date(form.endsAt).toISOString() : null }) }); const data = await response.json(); if (response.ok) { setForm(emptyForm()); setNotice("Comunicado publicado correctamente."); setTab("current"); await load(); } else setNotice(data.error ?? "No se pudo publicar el comunicado."); setSaving(false); }
  async function toggle(item: Announcement) { await fetch(`/api/announcements/${item.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ active: !item.active }) }); await load(); }

  return <div className="fixed inset-0 z-70 flex items-center justify-center bg-slate-950/65 p-3 backdrop-blur-sm sm:p-6" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><div role="dialog" aria-modal="true" aria-labelledby="announcements-title" className="flex max-h-[calc(100vh-1.5rem)] w-full max-w-4xl flex-col overflow-hidden rounded-3xl bg-white shadow-2xl sm:max-h-[calc(100vh-3rem)]"><header className="flex shrink-0 items-start justify-between border-b border-slate-200 p-5 sm:p-6"><div><p className="text-sm font-black text-blue-600">Información importante</p><h2 id="announcements-title" className="mt-1 text-2xl font-black text-slate-950">Centro de comunicados</h2><p className="mt-1 text-sm text-slate-500">Avisos operativos, horarios y mantenimientos.</p></div><button onClick={onClose} aria-label="Cerrar comunicados" className="rounded-xl p-2 text-slate-600 hover:bg-slate-100"><X /></button></header>{admin && <nav className="flex shrink-0 gap-2 border-b border-slate-200 px-5 py-3 sm:px-6"><Tab active={tab === "current"} onClick={() => setTab("current")}>Publicados</Tab><Tab active={tab === "create"} onClick={() => setTab("create")}>Nuevo comunicado</Tab></nav>}<main className="min-h-0 flex-1 overflow-y-auto overscroll-contain p-5 sm:p-6">{notice && <p role="status" className="mb-4 rounded-xl bg-blue-50 p-3 text-sm font-bold text-blue-800">{notice}</p>}{tab === "current" ? <AnnouncementList items={items} admin={admin} onToggle={toggle} /> : admin ? <AnnouncementForm form={form} setForm={setForm} chains={chains} users={users} saving={saving} onPublish={publish} /> : null}</main></div></div>;
}

function AnnouncementList({ items, admin, onToggle }: { items: Announcement[]; admin: boolean; onToggle: (item: Announcement) => void }) {
  if (!items.length) return <div className="py-14 text-center"><BellRing className="mx-auto h-10 w-10 text-slate-300" /><p className="mt-3 text-sm text-slate-500">No hay comunicados vigentes.</p></div>;
  return <div className="space-y-4">{items.map((item) => <article key={item.id} className={`rounded-2xl border p-5 ${item.active ? "border-blue-200 bg-blue-50/50" : "border-slate-200 bg-slate-50 opacity-70"}`}><div className="flex flex-col justify-between gap-4 sm:flex-row"><div className="flex min-w-0 gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-blue-600 text-white"><Megaphone className="h-5 w-5" /></span><div className="min-w-0"><h3 className="break-words font-black text-slate-950">{item.title}</h3><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-6 text-slate-700">{item.message}</p></div></div>{admin && <button onClick={() => onToggle(item)} className="h-fit shrink-0 rounded-xl border border-slate-300 bg-white px-3 py-2 text-xs font-black text-slate-700">{item.active ? "Desactivar" : "Reactivar"}</button>}</div><div className="mt-4 flex flex-wrap gap-2 text-xs font-bold text-slate-500"><Tag>{item.audience === "TODOS" ? "Todos" : item.audience === "CLIENTES" ? "Clientes" : "Analistas"}</Tag>{item.chain && <Tag>Cadena: {item.chain}</Tag>}{item.analyst && <Tag>Analista: {item.analyst}</Tag>}<Tag><CalendarClock className="mr-1 inline h-3 w-3" />Desde {new Date(item.startsAt).toLocaleString("es-MX")}</Tag>{item.endsAt && <Tag>Hasta {new Date(item.endsAt).toLocaleString("es-MX")}</Tag>}</div></article>)}</div>;
}

function AnnouncementForm({ form, setForm, chains, users, saving, onPublish }: { form: ReturnType<typeof emptyForm>; setForm: (form: ReturnType<typeof emptyForm>) => void; chains: Option[]; users: Option[]; saving: boolean; onPublish: () => void }) {
  return <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Título"><input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} maxLength={160} placeholder="Ej. Horario especial" className="input mt-1" /></Field><Field label="Dirigido a"><select value={form.audience} onChange={(event) => setForm({ ...form, audience: event.target.value, chainId: "", analystId: "" })} className="input mt-1 bg-white text-slate-950"><option value="TODOS">Todos</option><option value="CLIENTES">Clientes</option><option value="ANALISTAS">Analistas</option></select></Field>{form.audience === "CLIENTES" && <Field label="Cadena (opcional)"><select value={form.chainId} onChange={(event) => setForm({ ...form, chainId: event.target.value })} className="input mt-1 bg-white text-slate-950"><option value="">Todas las cadenas</option>{chains.map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</select></Field>}{form.audience === "ANALISTAS" && <Field label="Analista (opcional)"><select value={form.analystId} onChange={(event) => setForm({ ...form, analystId: event.target.value })} className="input mt-1 bg-white text-slate-950"><option value="">Todos los analistas</option>{users.filter((item) => item.role === "analista" && item.activo).map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</select></Field>}<Field label="Publicar desde"><input type="datetime-local" value={form.startsAt} onChange={(event) => setForm({ ...form, startsAt: event.target.value })} className="input mt-1" /></Field><Field label="Mostrar hasta (opcional)"><input type="datetime-local" value={form.endsAt} onChange={(event) => setForm({ ...form, endsAt: event.target.value })} className="input mt-1" /></Field></div><Field label="Mensaje"><textarea value={form.message} onChange={(event) => setForm({ ...form, message: event.target.value })} rows={7} maxLength={4000} placeholder="Explica qué ocurrirá, cuándo y qué deben hacer los usuarios." className="input mt-1 resize-y" /></Field><button onClick={onPublish} disabled={saving || form.title.trim().length < 3 || form.message.trim().length < 5 || !form.startsAt} className="inline-flex items-center gap-2 rounded-xl bg-blue-700 px-5 py-3 font-black text-white disabled:opacity-40"><Send className="h-4 w-4" />{saving ? "Publicando..." : "Publicar comunicado"}</button></div>;
}

function Tab({ active, onClick, children }: { active: boolean; onClick: () => void; children: React.ReactNode }) { return <button onClick={onClick} className={`rounded-xl px-4 py-2 text-sm font-black ${active ? "bg-blue-600 text-white" : "text-slate-600 hover:bg-slate-100"}`}>{children}</button>; }
function Tag({ children }: { children: React.ReactNode }) { return <span className="rounded-full bg-white px-2.5 py-1">{children}</span>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-bold text-slate-700">{label}{children}</label>; }
