"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertCircle, AlertTriangle, Bell, Building2, Clock3, Download, FileText, LayoutDashboard, Plus, Search, Settings2, UserRoundCog, Users, X } from "lucide-react";
import { UserMenu } from "@/components/shared/UserMenu";
import { WorkspaceHeader } from "@/components/shared/WorkspaceHeader";
import { PageHeader } from "@/components/shared/PageHeader";
import { CatalogEditor } from "@/components/admin/CatalogEditor";
import { ChainEditor } from "@/components/admin/ChainEditor";
import { TicketAssignmentPanel } from "@/components/admin/TicketAssignmentPanel";
import { AdminTicketDetail } from "@/components/admin/AdminTicketDetail";
import { TeamManager } from "@/components/admin/TeamManager";
import type { Chain, Ticket, TicketStatus, User } from "@/lib/types";
import { daysSince, fieldClass } from "@/lib/ui";

type Section = "overview" | "accounts" | "chains" | "catalog" | "tickets";
const inputClass = fieldClass;
const daysOpen = (ticket: Ticket) => daysSince(ticket.updatedAt || ticket.createdAt);

export default function AdminPage() {
  const [section, setSection] = useState<Section>("overview");
  const [users, setUsers] = useState<User[]>([]);
  const [chains, setChains] = useState<Chain[]>([]);
  const [tickets, setTickets] = useState<Ticket[]>([]);
  const [editingChain, setEditingChain] = useState<Chain | null>(null);
  const [selectedTicket, setSelectedTicket] = useState<Ticket | null>(null);
  const [notice, setNotice] = useState<{ type: "success" | "error"; text: string } | null>(null);
  const [newChain, setNewChain] = useState({ nombre: "", descripcion: "" });
  const [chainSearch, setChainSearch] = useState("");
  const [chainStatus, setChainStatus] = useState("all");
  const [ticketStatus, setTicketStatus] = useState<TicketStatus | "all">("all");
  const [ticketChain, setTicketChain] = useState("all");
  const [ticketAnalyst, setTicketAnalyst] = useState("all");
  const [dateFrom, setDateFrom] = useState("");
  const [dateTo, setDateTo] = useState("");
  const [notificationTarget, setNotificationTarget] = useState<User | null>(null);
  const [notificationMessage, setNotificationMessage] = useState("");
  const [sendingNotification, setSendingNotification] = useState(false);

  useEffect(() => { Promise.all([fetch("/api/users").then((r) => r.json()), fetch("/api/chains").then((r) => r.json()), fetch("/api/tickets").then((r) => r.json())]).then(([userData, chainData, ticketData]) => { if (Array.isArray(userData)) setUsers(userData); if (Array.isArray(chainData)) setChains(chainData); if (Array.isArray(ticketData)) setTickets(ticketData); }); }, []);
  const analysts = users.filter((user) => user.role === "analista");
  const overdue = useMemo(() => tickets.filter((ticket) => ticket.estado !== "cerrado" && daysOpen(ticket) > 5), [tickets]);
  const filteredTickets = useMemo(() => tickets.filter((ticket) => {
    const created = new Date(ticket.createdAt);
    return (ticketStatus === "all" || ticket.estado === ticketStatus) && (ticketChain === "all" || ticket.cadena === ticketChain) && (ticketAnalyst === "all" || (ticketAnalyst === "unassigned" ? !ticket.asignadoA : ticket.asignadoA === ticketAnalyst)) && (!dateFrom || created >= new Date(`${dateFrom}T00:00:00`)) && (!dateTo || created <= new Date(`${dateTo}T23:59:59`));
  }), [tickets, ticketStatus, ticketChain, ticketAnalyst, dateFrom, dateTo]);
  const filteredChains = chains.filter((chain) => chain.nombre.toLowerCase().includes(chainSearch.toLowerCase()) && (chainStatus === "all" || (chainStatus === "active" ? chain.activa : !chain.activa)));
  const alert = (type: "success" | "error", text: string) => { setNotice({ type, text }); window.setTimeout(() => setNotice(null), 4500); };

  async function createChain() { const response = await fetch("/api/chains", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(newChain) }); const data = await response.json(); if (!response.ok) return alert("error", data.error ?? "No se pudo crear la cadena."); setChains((current) => [data, ...current]); setNewChain({ nombre: "", descripcion: "" }); alert("success", "Cadena creada correctamente."); }
  async function exportAltas() { if (!filteredTickets.length) return alert("error", "No hay folios con los filtros actuales."); const response = await fetch("/api/tickets/export", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ids: filteredTickets.map((ticket) => ticket.id), mode: "all" }) }); if (!response.ok) return alert("error", (await response.json()).error ?? "No se pudo generar el reporte."); const url = URL.createObjectURL(await response.blob()); const link = document.createElement("a"); link.href = url; link.download = `reporte-folios-${new Date().toISOString().slice(0, 10)}.xlsx`; link.click(); URL.revokeObjectURL(url); }
  async function sendNotification() { if (!notificationTarget || !notificationMessage.trim()) return; setSendingNotification(true); const response = await fetch("/api/notifications", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ recipientId: notificationTarget.id, message: notificationMessage }) }); const data = await response.json(); setSendingNotification(false); if (!response.ok) return alert("error", data.error ?? "No se pudo enviar la notificación."); setNotificationTarget(null); setNotificationMessage(""); alert("success", "Notificación enviada al analista."); }

  const nav = [{ id: "overview", label: "Resumen", icon: LayoutDashboard }, { id: "tickets", label: "Folios", icon: FileText }, { id: "chains", label: "Cadenas", icon: Building2 }, { id: "accounts", label: "Equipo", icon: Users }, { id: "catalog", label: "Catálogo", icon: Settings2 }] as const;
  return <div className="min-h-screen bg-[#f4f7fb] text-slate-900">{notice && <div role="status" className={`fixed right-4 top-4 z-70 max-w-sm rounded-xl px-5 py-3 font-semibold text-white shadow-xl ${notice.type === "success" ? "bg-emerald-600" : "bg-red-600"}`}>{notice.text}</div>}
    <WorkspaceHeader eyebrow="Centro de control KAM" title="Administración operativa" active={section} items={nav} onNavigate={setSection} onHome={() => setSection("overview")} actions={<UserMenu dark />} />
    <main className="mx-auto max-w-7xl px-4 py-7 sm:px-6">
      {section === "accounts" && <div className="space-y-6"><SectionTitle eyebrow="Equipo" title="Usuarios, analistas y clientes" description="Administra accesos por tipo de cuenta, estado y contraseña." /><TeamManager users={users} onUsersChange={setUsers} /></div>}
      {section === "overview" && <div className="space-y-7"><section className="rounded-3xl bg-linear-to-br from-slate-900 to-blue-950 p-7 text-white shadow-xl"><p className="text-sm font-bold text-blue-300">Visión ejecutiva</p><h2 className="mt-1 text-3xl font-black">Operación, clientes y equipo</h2><p className="mt-2 max-w-2xl text-slate-300">Detecta riesgos, carga de trabajo y cadenas que necesitan atención sin recorrer toda la aplicación.</p></section>{overdue.length > 0 && <button onClick={() => { setTicketStatus("all"); setSection("tickets"); }} className="flex w-full items-start gap-3 rounded-2xl border border-red-200 bg-red-50 p-4 text-left"><AlertTriangle className="mt-0.5 h-6 w-6 shrink-0 text-red-600" /><span><strong className="text-red-900">{overdue.length} folios llevan más de 5 días sin actualización</strong><span className="mt-1 block text-sm text-red-700">Haz clic para revisarlos. Se destacan en rojo dentro de Folios.</span></span></button>}
        <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Kpi label="Usuarios" value={users.length} icon={<Users />} color="blue" onClick={() => setSection("accounts")} /><Kpi label="Cadenas" value={chains.length} icon={<Building2 />} color="emerald" onClick={() => setSection("chains")} /><Kpi label="Tickets" value={tickets.length} icon={<Clock3 />} color="purple" onClick={() => setSection("tickets")} /><Kpi label="Retrasados" value={overdue.length} icon={<AlertCircle />} color="red" onClick={() => setSection("tickets")} /></section>
        <section><div className="flex items-end justify-between"><div><p className="text-sm font-bold text-blue-600">Supervisión</p><h2 className="text-2xl font-black">Carga de analistas</h2></div></div><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{analysts.map((analyst) => { const assigned = tickets.filter((ticket) => ticket.asignadoA === analyst.nombre && ticket.estado !== "cerrado"); const delayed = assigned.filter((ticket) => daysOpen(ticket) > 5); const latest = tickets.filter((ticket) => ticket.asignadoA === analyst.nombre).sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime())[0]; return <article key={analyst.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 font-black text-blue-700">{analyst.nombre.slice(0, 2).toUpperCase()}</span><div><h3 className="font-black">{analyst.nombre}</h3><p className="text-xs text-slate-500">{analyst.activo ? "Cuenta activa" : "Cuenta bloqueada"}</p></div></div><button onClick={() => setNotificationTarget(analyst)} aria-label={`Notificar a ${analyst.nombre}`} className="rounded-lg p-2 text-blue-700 hover:bg-blue-50"><Bell className="h-5 w-5" /></button></div><div className="mt-4 grid grid-cols-2 gap-3"><Metric label="Abiertos" value={assigned.length} /><Metric label="Con alerta" value={delayed.length} danger={delayed.length > 0} /></div><p className="mt-4 text-xs text-slate-500">Último movimiento: {latest ? new Date(latest.updatedAt).toLocaleString("es-MX") : "Sin actividad registrada"}</p><button onClick={() => { setTicketAnalyst(analyst.nombre); setSection("tickets"); }} className="mt-4 text-sm font-bold text-blue-700">Ver folios asignados →</button></article>; })}</div></section></div>}


      {section === "chains" && <div className="space-y-6"><SectionTitle eyebrow="Cartera" title="Cadenas y clientes" description="Administra códigos, condiciones comerciales, estado y riesgo de cada cadena." /><section className="grid gap-6 lg:grid-cols-[360px_1fr]"><div className="h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-black">Agregar cadena</h3><div className="mt-4 space-y-3"><input className={inputClass} placeholder="Nombre de la cadena" value={newChain.nombre} onChange={(e) => setNewChain({ ...newChain, nombre: e.target.value })} /><textarea className={`${inputClass} resize-none`} rows={4} placeholder="Descripción y contexto comercial" value={newChain.descripcion} onChange={(e) => setNewChain({ ...newChain, descripcion: e.target.value })} /><button onClick={createChain} disabled={!newChain.nombre.trim()} className="w-full rounded-xl bg-emerald-700 px-4 py-3 font-bold text-white disabled:opacity-40"><Plus className="mr-2 inline h-4 w-4" />Crear cadena</button></div></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 grid gap-3 sm:grid-cols-[1fr_180px]"><div className="relative"><Search className="absolute left-3 top-3 h-5 w-5 text-slate-400" /><input className={`${inputClass} pl-10`} placeholder="Buscar cadena" value={chainSearch} onChange={(e) => setChainSearch(e.target.value)} /></div><select className={inputClass} value={chainStatus} onChange={(e) => setChainStatus(e.target.value)}><option value="all">Todas</option><option value="active">Activas</option><option value="inactive">Inactivas</option></select></div><div className="space-y-3">{filteredChains.map((chain) => <article key={chain.id} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><div className="flex items-center gap-2"><h3 className="font-black">{chain.nombre}</h3><span className={`rounded-full px-2 py-0.5 text-xs font-bold ${chain.activa ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{chain.activa ? "Activa" : "Inactiva"}</span></div><p className="mt-1 text-sm text-slate-500">{chain.descripcion || "Sin descripción"}</p><p className="mt-3 text-sm"><strong>{chain.clientCount ?? 0}</strong> códigos · <strong>{chain.ticketCount ?? 0}</strong> folios</p></div><button onClick={() => setEditingChain(chain)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white"><UserRoundCog className="h-4 w-4" />Editar y administrar</button></div></article>)}</div></div></section></div>}

      {section === "catalog" && <div className="space-y-6"><SectionTitle eyebrow="Configuración" title="Catálogo del portal" description="Define qué reportes puede levantar el cliente y qué información debe capturar." /><CatalogEditor /></div>}

      {section === "tickets" && <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><SectionTitle eyebrow="Operación" title="Supervisión de folios" description="Filtra por analista, cadena, fecha y estado. Los folios sin actualización por más de 5 días se muestran en rojo." /><button onClick={exportAltas} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-700 px-4 py-3 text-sm font-bold text-white"><Download className="h-4 w-4" />Descargar Excel</button></div><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><select className={inputClass} value={ticketAnalyst} onChange={(e) => setTicketAnalyst(e.target.value)}><option value="all">Todos los analistas</option><option value="unassigned">Sin asignar</option>{analysts.map((analyst) => <option key={analyst.id} value={analyst.nombre}>{analyst.nombre}</option>)}</select><select className={inputClass} value={ticketChain} onChange={(e) => setTicketChain(e.target.value)}><option value="all">Todas las cadenas</option>{chains.map((chain) => <option key={chain.id} value={chain.nombre}>{chain.nombre}</option>)}</select><select className={inputClass} value={ticketStatus} onChange={(e) => setTicketStatus(e.target.value as TicketStatus | "all")}><option value="all">Todos los estados</option><option value="pendiente">Pendiente</option><option value="seguimiento">Seguimiento</option><option value="espera_cliente">Espera del cliente</option><option value="cerrado">Cerrado</option></select><label className="text-xs font-bold text-slate-600">Desde<input type="date" className={`${inputClass} mt-1`} value={dateFrom} onChange={(e) => setDateFrom(e.target.value)} /></label><label className="text-xs font-bold text-slate-600">Hasta<input type="date" className={`${inputClass} mt-1`} value={dateTo} onChange={(e) => setDateTo(e.target.value)} /></label></div><p className="mt-4 text-sm font-semibold text-slate-500">{filteredTickets.length} folios encontrados</p></section><TicketAssignmentPanel tickets={filteredTickets} analysts={analysts} onOpen={setSelectedTicket} onUpdated={(updated) => setTickets((current) => current.map((ticket) => ticket.id === updated.id ? updated : ticket))} /></div>}
    </main>
    {editingChain && <ChainEditor chain={editingChain} onClose={() => setEditingChain(null)} onSaved={(updated) => { setChains((current) => current.map((item) => item.id === updated.id ? updated : item)); setEditingChain(updated); alert("success", "Cadena actualizada."); }} onDeleted={(id) => { setChains((current) => current.filter((item) => item.id !== id)); setTickets((current) => current.filter((ticket) => ticket.cadena !== editingChain.nombre)); alert("success", "Cadena y datos relacionados eliminados."); }} />}
    {selectedTicket && <AdminTicketDetail ticket={selectedTicket} analysts={analysts} onClose={() => setSelectedTicket(null)} onUpdated={(updated) => { setSelectedTicket(updated); setTickets((current) => current.map((ticket) => ticket.id === updated.id ? updated : ticket)); }} />}
    {notificationTarget && <div className="fixed inset-0 z-60 grid place-items-center bg-slate-950/60 p-4"><div role="dialog" aria-modal="true" className="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-sm font-bold text-blue-600">Notificación interna</p><h2 className="text-xl font-black">{notificationTarget.nombre}</h2></div><button onClick={() => setNotificationTarget(null)} aria-label="Cerrar"><X /></button></div><textarea autoFocus rows={5} value={notificationMessage} onChange={(e) => setNotificationMessage(e.target.value)} placeholder="Describe la prioridad, seguimiento o acción requerida" className={`${inputClass} mt-5 resize-none`} /><button onClick={sendNotification} disabled={sendingNotification || !notificationMessage.trim()} className="mt-4 w-full rounded-xl bg-blue-700 px-4 py-3 font-bold text-white disabled:opacity-40">{sendingNotification ? "Enviando..." : "Enviar al analista"}</button></div></div>}
  </div>;
}

const SectionTitle = PageHeader;
function Kpi({ label, value, icon, color, onClick }: { label: string; value: number; icon: React.ReactNode; color: "blue" | "emerald" | "purple" | "red"; onClick: () => void }) { const tones = { blue: "bg-blue-50 text-blue-700", emerald: "bg-emerald-50 text-emerald-700", purple: "bg-purple-50 text-purple-700", red: "bg-red-50 text-red-700" }; return <button onClick={onClick} className="rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-center justify-between"><div><p className="text-sm font-bold text-slate-500">{label}</p><p className="mt-1 text-3xl font-black">{value}</p><p className="mt-2 text-xs font-bold text-blue-600">Abrir sección →</p></div><span className={`grid h-12 w-12 place-items-center rounded-xl [&>svg]:h-6 [&>svg]:w-6 ${tones[color]}`}>{icon}</span></div></button>; }
function Metric({ label, value, danger = false }: { label: string; value: number; danger?: boolean }) { return <div className={`rounded-xl p-3 ${danger ? "bg-red-50" : "bg-slate-50"}`}><p className="text-xs font-bold text-slate-500">{label}</p><p className={`mt-1 text-2xl font-black ${danger ? "text-red-700" : "text-slate-900"}`}>{value}</p></div>; }
