"use client";

import { useEffect, useState } from "react";
import { ChevronDown, Plus, Save, Trash2 } from "lucide-react";
import { DEFAULT_REPORT_CATALOG, mergeReportCatalog, type ReportCategory, type ReportDefinition, type ReportField } from "@/lib/report-catalog";

const createField = (): ReportField => ({ key: `field-${Date.now()}`, label: "NUEVO CAMPO", type: "text", required: true });
const createReport = (): ReportDefinition => ({ id: `report-${Date.now()}`, name: "NUEVO REPORTE", active: true, fields: [createField()] });

export function CatalogEditor() {
  const [catalog, setCatalog] = useState<ReportCategory[]>(DEFAULT_REPORT_CATALOG);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/report-catalog").then((response) => response.json()).then((data: ReportCategory[]) => { if (Array.isArray(data)) setCatalog(mergeReportCatalog(data)); }); }, []);
  const updateCategory = (index: number, update: (value: ReportCategory) => ReportCategory) => setCatalog((current) => current.map((item, position) => position === index ? update(item) : item));
  const save = async () => { setSaving(true); const response = await fetch("/api/report-catalog", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(catalog) }); const data = await response.json(); setMessage(response.ok ? "Catálogo guardado correctamente." : data.error ?? "No se pudo guardar."); setSaving(false); };
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7">
    <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div><p className="text-sm font-bold text-purple-600">Configuración</p><h2 className="text-2xl font-black">Catálogo de reportes</h2><p className="mt-1 text-sm text-slate-500">Abre una categoría para editar opciones y campos existentes.</p></div><div className="flex gap-2"><button onClick={() => setCatalog((current) => [...current, { id: `category-${Date.now()}`, name: "NUEVA CATEGORIA", active: true, reports: [createReport()] }])} className="rounded-xl border px-4 py-2 text-sm font-bold"><Plus className="mr-1 inline h-4 w-4" />Categoría</button><button onClick={save} disabled={saving} className="rounded-xl bg-purple-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-40"><Save className="mr-1 inline h-4 w-4" />{saving ? "Guardando" : "Guardar"}</button></div></div>
    {message && <p role="status" className="mt-4 rounded-xl bg-blue-50 p-3 text-sm font-semibold text-blue-800">{message}</p>}
    <div className="mt-6 space-y-3">{catalog.map((category, categoryIndex) => <CategoryEditor key={category.id} category={category} update={(next) => updateCategory(categoryIndex, () => next)} remove={() => setCatalog((current) => current.filter((_, index) => index !== categoryIndex))} />)}</div>
  </section>;
}

function CategoryEditor({ category, update, remove }: { category: ReportCategory; update: (value: ReportCategory) => void; remove: () => void }) {
  const updateReport = (index: number, next: ReportDefinition) => update({ ...category, reports: category.reports.map((report, position) => position === index ? next : report) });
  return <details className="group rounded-2xl border border-slate-200"><summary className="cursor-pointer list-none p-4"><div className="flex items-center gap-3"><ChevronDown className="h-5 w-5 shrink-0 transition group-open:rotate-180" /><input aria-label="Nombre de categoría" value={category.name} onClick={(event) => event.stopPropagation()} onChange={(event) => update({ ...category, name: event.target.value.toUpperCase() })} className="min-w-0 flex-1 rounded-lg border px-3 py-2 font-black" /><label onClick={(event) => event.stopPropagation()} className="text-sm font-bold"><input type="checkbox" checked={category.active} onChange={(event) => update({ ...category, active: event.target.checked })} className="mr-2" />Activa</label><button onClick={(event) => { event.preventDefault(); remove(); }} aria-label="Eliminar categoría" className="p-2 text-red-600"><Trash2 className="h-4 w-4" /></button></div></summary><div className="space-y-4 border-t p-4">{category.reports.map((report, index) => <ReportEditor key={report.id} report={report} update={(next) => updateReport(index, next)} remove={() => update({ ...category, reports: category.reports.filter((_, position) => position !== index) })} />)}<button onClick={() => update({ ...category, reports: [...category.reports, createReport()] })} className="text-sm font-bold text-purple-700"><Plus className="mr-1 inline h-4 w-4" />Agregar reporte</button></div></details>;
}

function ReportEditor({ report, update, remove }: { report: ReportDefinition; update: (value: ReportDefinition) => void; remove: () => void }) {
  return <div className="rounded-xl bg-slate-50 p-4"><div className="flex flex-wrap gap-2"><input aria-label="Nombre del reporte" value={report.name} onChange={(event) => update({ ...report, name: event.target.value.toUpperCase() })} className="min-w-60 flex-1 rounded-lg border bg-white px-3 py-2 font-bold" /><label className="rounded-lg bg-white px-3 py-2 text-xs font-bold"><input type="checkbox" checked={report.active} onChange={(event) => update({ ...report, active: event.target.checked })} className="mr-2" />Visible</label><button onClick={remove} aria-label="Eliminar reporte" className="p-2 text-red-600"><Trash2 className="h-4 w-4" /></button></div><div className="mt-3 space-y-2">{report.fields.map((field, index) => <div key={`${field.key}-${index}`} className="grid gap-2 rounded-xl border bg-white p-3 sm:grid-cols-[1fr_130px_110px_40px]"><input aria-label="Nombre del campo" value={field.label} onChange={(event) => update({ ...report, fields: report.fields.map((item, position) => position === index ? { ...item, label: event.target.value.toUpperCase() } : item) })} className="rounded-lg border px-3 py-2 text-sm font-semibold" /><select aria-label="Tipo" value={field.type} onChange={(event) => update({ ...report, fields: report.fields.map((item, position) => position === index ? { ...item, type: event.target.value as ReportField["type"] } : item) })} className="rounded-lg border px-2 text-sm"><option value="text">Texto</option><option value="date">Fecha</option><option value="email">Correo</option><option value="number">Número</option></select><label className="self-center text-xs font-bold"><input type="checkbox" checked={field.required} onChange={(event) => update({ ...report, fields: report.fields.map((item, position) => position === index ? { ...item, required: event.target.checked } : item) })} className="mr-2" />Obligatorio</label><button onClick={() => update({ ...report, fields: report.fields.filter((_, position) => position !== index) })} aria-label="Eliminar campo" className="text-red-600"><Trash2 className="h-4 w-4" /></button></div>)}</div><button onClick={() => update({ ...report, fields: [...report.fields, createField()] })} className="mt-3 text-sm font-bold text-blue-700"><Plus className="mr-1 inline h-4 w-4" />Agregar campo</button></div>;
}
