"use client";

import { useCallback, useEffect, useState } from "react";
import { Download, FileSpreadsheet, Plus, Save, Trash2, Upload, X } from "lucide-react";
import type { Chain, CommercialCondition } from "@/lib/types";

const empty: CommercialCondition = { credit: "", contract: "", guarantee: "", collection: "", collectionPortal: "", segment: "", priceList: "", discount: "", promoList: "", continent: "", scheme: "", creditDays: "", pinc: "", cashAndCredit: "", comments: "" };
const labels: Record<keyof CommercialCondition, string> = { credit: "Crédito", contract: "Contrato", guarantee: "Garantía", collection: "Cobranza", collectionPortal: "Portal cobranza", segment: "Segmento", priceList: "Lista de precios", discount: "Descuento", promoList: "Lista promocional", continent: "Continente", scheme: "Esquema", creditDays: "Días de crédito", pinc: "PINC", cashAndCredit: "Cash & Credit", comments: "Comentarios" };
type ClientRow = { id: string; customerNumber: string; name: string; active: boolean };

export function ChainEditor({ chain, onClose, onSaved, onDeleted }: { chain: Chain; onClose: () => void; onSaved: (chain: Chain) => void; onDeleted: (id: string) => void }) {
  const [name, setName] = useState(chain.nombre); const [description, setDescription] = useState(chain.descripcion); const [active, setActive] = useState(chain.activa);
  const [commercial, setCommercial] = useState<CommercialCondition>({ ...empty, ...chain.commercial }); const [clients, setClients] = useState<ClientRow[]>([]);
  const [code, setCode] = useState(""); const [clientName, setClientName] = useState(""); const [file, setFile] = useState<File | null>(null);
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [danger, setDanger] = useState(false); const [phrase, setPhrase] = useState(""); const [confirmation, setConfirmation] = useState("");
  const loadClients = useCallback(() => fetch(`/api/chains/${chain.id}/clients`).then((response) => response.json()).then((data) => { if (Array.isArray(data)) setClients(data); }), [chain.id]);
  useEffect(() => { void loadClients(); }, [loadClients]);
  async function save() { setSaving(true); const response = await fetch(`/api/chains/${chain.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ nombre: name, descripcion: description, active, commercial }) }); const data = await response.json(); if (response.ok) { onSaved({ ...chain, nombre: name, descripcion: description, activa: active, commercial, clientCount: clients.length }); setMessage("Cadena y condiciones guardadas."); } else setMessage(data.error ?? "No fue posible guardar."); setSaving(false); }
  async function addClient() { const response = await fetch(`/api/chains/${chain.id}/clients`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ code, name: clientName }) }); const data = await response.json(); if (response.ok) { setCode(""); setClientName(""); await loadClients(); setMessage("Código agregado correctamente."); } else setMessage(data.error ?? "No se pudo agregar el código."); }
  async function importClients() { if (!file) return; setSaving(true); const body = new FormData(); body.append("file", file); const response = await fetch(`/api/chains/${chain.id}/clients`, { method: "POST", body }); const data = await response.json(); if (response.ok) { await loadClients(); setFile(null); setMessage(`${data.imported} códigos importados.`); } else setMessage(data.error ?? "No se pudo importar."); setSaving(false); }
  async function remove() { setSaving(true); const response = await fetch(`/api/chains/${chain.id}`, { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ phrase, confirmation }) }); const data = await response.json(); if (response.ok) { onDeleted(chain.id); onClose(); } else { setMessage(data.error ?? "No se pudo eliminar."); setSaving(false); } }
  return <div className="fixed inset-0 z-60 overflow-y-auto bg-slate-950/60 p-4"><div role="dialog" aria-modal="true" className="mx-auto my-5 max-w-5xl rounded-3xl bg-white shadow-2xl"><header className="sticky top-0 z-10 flex justify-between rounded-t-3xl border-b bg-white p-6"><div><p className="text-sm font-bold text-blue-600">Administrar cadena</p><h2 className="text-2xl font-black">{chain.nombre}</h2><p className="text-sm text-slate-500">{clients.length} códigos · {chain.ticketCount ?? 0} folios</p></div><button onClick={onClose} aria-label="Cerrar"><X /></button></header><div className="space-y-7 p-6">
    <section><h3 className="font-black">Datos generales</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Nombre<input value={name} onChange={(e) => setName(e.target.value)} className="input mt-1" /></label><label className="flex items-center gap-2 self-end rounded-xl bg-slate-50 p-3 text-sm font-bold"><input type="checkbox" checked={active} onChange={(e) => setActive(e.target.checked)} />Cadena activa</label></div><label className="mt-3 block text-sm font-bold">Descripción<textarea value={description} onChange={(e) => setDescription(e.target.value)} rows={3} className="input mt-1 resize-none" /></label></section>
    <section><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h3 className="font-black">Códigos de cliente</h3><p className="text-sm text-slate-500">Excel debe contener CODIGO y NOMBRE en la primera fila.</p></div><a href={`/api/chains/${chain.id}/export`} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-bold text-white"><Download className="h-4 w-4" />Exportar clientes</a></div><div className="mt-4 grid gap-2 sm:grid-cols-[150px_1fr_auto]"><input value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, "").slice(0, 9))} placeholder="Código 9 dígitos" className="input" /><input value={clientName} onChange={(e) => setClientName(e.target.value.toUpperCase())} placeholder="Nombre del cliente o sucursal" className="input" /><button onClick={addClient} disabled={!/^\d{9}$/.test(code) || clientName.trim().length < 2} className="rounded-xl bg-blue-700 px-4 text-sm font-bold text-white disabled:opacity-40"><Plus className="mr-1 inline h-4 w-4" />Agregar</button></div><div className="mt-3 flex flex-col gap-3 rounded-xl border border-dashed p-4 sm:flex-row sm:items-center"><FileSpreadsheet className="h-7 w-7 text-emerald-700" /><input type="file" accept=".xlsx,.xls" onChange={(e) => setFile(e.target.files?.[0] ?? null)} className="flex-1 text-sm" /><button onClick={importClients} disabled={!file || saving} className="rounded-xl border border-emerald-300 px-4 py-2 text-sm font-bold text-emerald-800 disabled:opacity-40"><Upload className="mr-1 inline h-4 w-4" />Importar</button></div><div className="mt-3 max-h-48 overflow-y-auto rounded-xl border"><table className="w-full text-sm"><thead className="sticky top-0 bg-slate-100"><tr><th className="p-2 text-left">Código</th><th className="p-2 text-left">Nombre</th></tr></thead><tbody>{clients.map((client) => <tr key={client.id} className="border-t"><td className="p-2 font-mono">{client.customerNumber}</td><td className="p-2">{client.name}</td></tr>)}</tbody></table></div></section>
    <section><h3 className="font-black">Condiciones comerciales</h3><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{(Object.keys(labels) as Array<keyof CommercialCondition>).map((key) => <label key={key} className={`text-sm font-bold ${key === "comments" ? "sm:col-span-2 lg:col-span-3" : ""}`}>{labels[key]}{key === "comments" ? <textarea value={commercial[key]} onChange={(e) => setCommercial({ ...commercial, [key]: e.target.value })} rows={3} className="input mt-1 resize-none" /> : <input value={commercial[key]} onChange={(e) => setCommercial({ ...commercial, [key]: e.target.value })} className="input mt-1" />}</label>)}</div></section>
    {message && <p role="status" className="rounded-xl bg-blue-50 p-3 text-sm font-bold text-blue-800">{message}</p>}<div className="flex flex-col justify-between gap-3 border-t pt-5 sm:flex-row"><button onClick={() => setDanger(!danger)} className="rounded-xl border border-red-200 px-4 py-3 text-sm font-bold text-red-700"><Trash2 className="mr-1 inline h-4 w-4" />Eliminar cadena</button><button onClick={save} disabled={saving || !name.trim()} className="rounded-xl bg-blue-700 px-5 py-3 text-sm font-bold text-white disabled:opacity-40"><Save className="mr-1 inline h-4 w-4" />Guardar cambios</button></div>{danger && <div className="rounded-2xl border-2 border-red-300 bg-red-50 p-5"><h3 className="font-black text-red-900">Eliminación irreversible</h3><p className="mt-1 text-sm text-red-800">Se eliminarán códigos, folios, sucursales, comentarios y archivos.</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><input value={phrase} onChange={(e) => setPhrase(e.target.value.toUpperCase())} placeholder="Escribe ELIMINAR" className="input border-red-300" /><input value={confirmation} onChange={(e) => setConfirmation(e.target.value)} placeholder={`Escribe ${chain.nombre}`} className="input border-red-300" /></div><button onClick={remove} disabled={saving || phrase !== "ELIMINAR" || confirmation !== chain.nombre} className="mt-3 rounded-xl bg-red-700 px-4 py-3 text-sm font-black text-white disabled:opacity-30">Eliminar definitivamente</button></div>}
  </div></div></div>;
}
