"use client";

import { useState } from "react";
import { Eye, EyeOff, KeyRound, Plus, Search, X } from "lucide-react";
import type { User } from "@/lib/types";

type Tab = "staff" | "clients";
const fieldClass = "w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-slate-950 placeholder:text-slate-500";
export function TeamManager({ users, onUsersChange }: { users: User[]; onUsersChange: (users: User[]) => void }) {
  const [tab, setTab] = useState<Tab>("staff"); const [search, setSearch] = useState(""); const [resetUser, setResetUser] = useState<User | null>(null); const [password, setPassword] = useState(""); const [message, setMessage] = useState("");
  const [newUser, setNewUser] = useState({ nombre: "", email: "", password: "", role: "analista" });
  const visible = users.filter((user) => (tab === "clients" ? user.role === "cliente" : user.role !== "cliente") && `${user.nombre} ${user.email} ${user.chain ?? ""}`.toLowerCase().includes(search.toLowerCase()));
  async function create() { const response = await fetch("/api/users", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(newUser) }); const data = await response.json(); if (response.ok) { onUsersChange([data, ...users]); setNewUser({ nombre: "", email: "", password: "", role: "analista" }); setMessage("Usuario creado."); } else setMessage(data.error ?? "No se pudo crear."); }
  async function toggle(user: User) { const response = await fetch(`/api/users/${user.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ active: !user.activo }) }); if (response.ok) onUsersChange(users.map((item) => item.id === user.id ? { ...item, activo: !item.activo } : item)); }
  async function resetPassword() { if (!resetUser || password.length < 8) return; const response = await fetch(`/api/users/${resetUser.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password }) }); const data = await response.json(); if (response.ok) { setResetUser(null); setPassword(""); setMessage("Contraseña actualizada correctamente."); } else setMessage(data.error ?? "No se pudo actualizar la contraseña."); }
  return <div className="space-y-6"><div className="flex gap-2 rounded-2xl bg-slate-200 p-1.5"><button onClick={() => setTab("staff")} className={`flex-1 rounded-xl px-4 py-3 text-sm font-black ${tab === "staff" ? "bg-white text-blue-800 shadow" : "text-slate-600"}`}>Administradores y analistas ({users.filter((item) => item.role !== "cliente").length})</button><button onClick={() => setTab("clients")} className={`flex-1 rounded-xl px-4 py-3 text-sm font-black ${tab === "clients" ? "bg-white text-blue-800 shadow" : "text-slate-600"}`}>Clientes ({users.filter((item) => item.role === "cliente").length})</button></div>{message && <p role="status" className="rounded-xl bg-blue-50 p-3 text-sm font-bold text-blue-800">{message}</p>}
    <div className={`grid gap-6 ${tab === "staff" ? "lg:grid-cols-[350px_1fr]" : ""}`}>{tab === "staff" && <section className="h-fit rounded-2xl border bg-white p-5"><h3 className="font-black">Crear acceso interno</h3><div className="mt-4 space-y-3"><input className={fieldClass} placeholder="Nombre completo" value={newUser.nombre} onChange={(e) => setNewUser({ ...newUser, nombre: e.target.value })} /><input className={fieldClass} type="email" placeholder="correo@empresa.com" value={newUser.email} onChange={(e) => setNewUser({ ...newUser, email: e.target.value })} /><input className={fieldClass} type="password" placeholder="Contraseña temporal" value={newUser.password} onChange={(e) => setNewUser({ ...newUser, password: e.target.value })} /><select className={fieldClass} value={newUser.role} onChange={(e) => setNewUser({ ...newUser, role: e.target.value })}><option value="analista">Analista</option><option value="admin">Administrador</option></select><button onClick={create} disabled={!newUser.nombre || !newUser.email || newUser.password.length < 8} className="w-full rounded-xl bg-blue-700 p-3 font-bold text-white disabled:opacity-40"><Plus className="mr-1 inline h-4 w-4" />Crear usuario</button></div></section>}<section className="rounded-2xl border bg-white p-5"><div className="relative"><Search className="absolute left-3 top-3.5 h-5 w-5 text-slate-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar nombre, correo o cadena" className={`${fieldClass} pl-10`} /></div><div className="mt-4 space-y-2">{visible.map((user) => <article key={user.id} className="flex flex-col justify-between gap-3 rounded-xl border p-4 sm:flex-row sm:items-center"><div><p className="font-black">{user.nombre}</p><p className="text-sm text-slate-500">{user.email} · {user.role}</p>{user.role === "cliente" && <p className="mt-1 text-xs font-bold text-blue-700">{user.chain ?? "Sin cadena"} · {user.customerNumber ?? "Sin código"}</p>}</div><div className="flex gap-2"><button onClick={() => { setResetUser(user); setPassword(""); }} title="Modificar contraseña" className="rounded-lg p-2 text-blue-700 hover:bg-blue-50"><KeyRound className="h-5 w-5" /></button><button onClick={() => toggle(user)} title={user.activo ? "Bloquear" : "Activar"} className="rounded-lg p-2 hover:bg-slate-100">{user.activo ? <EyeOff className="h-5 w-5" /> : <Eye className="h-5 w-5" />}</button></div></article>)}</div></section></div>
    {resetUser && <div className="fixed inset-0 z-70 grid place-items-center bg-slate-950/60 p-4"><div role="dialog" aria-modal="true" className="w-full max-w-md rounded-3xl bg-white p-6"><div className="flex justify-between"><div><p className="text-sm font-bold text-blue-600">Modificar contraseña</p><h2 className="text-xl font-black">{resetUser.nombre}</h2></div><button onClick={() => setResetUser(null)}><X /></button></div><input autoFocus type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Nueva contraseña, mínimo 8 caracteres" className={`${fieldClass} mt-5`} /><button onClick={resetPassword} disabled={password.length < 8} className="mt-3 w-full rounded-xl bg-blue-700 p-3 font-bold text-white disabled:opacity-40"><KeyRound className="mr-1 inline h-4 w-4" />Actualizar contraseña</button></div></div>}
  </div>;
}
