"use client";

import { useState } from "react";
import type { Ticket, TicketStatus, User } from "@/lib/types";

export function TicketAssignmentPanel({ tickets, analysts, onUpdated }: { tickets: Ticket[]; analysts: User[]; onUpdated: (ticket: Ticket) => void }) {
  const [saving, setSaving] = useState("");
  const [message, setMessage] = useState("");
  async function update(id: string, body: { assignedToId?: string | null; status?: TicketStatus }) { setSaving(id); setMessage(""); const response = await fetch(`/api/tickets/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (response.ok) onUpdated(data); else setMessage(data.error ?? "No se pudo actualizar el folio."); setSaving(""); }
  return <section className="mb-6 rounded-2xl border border-blue-200 bg-blue-50/60 p-5"><div><p className="text-sm font-bold text-blue-700">Acciones administrativas</p><h2 className="text-xl font-black text-slate-950">Asignación y control de folios</h2><p className="mt-1 text-sm text-slate-600">Los cambios se registran en el historial del folio.</p></div>{message && <p role="alert" className="mt-3 rounded-lg bg-red-50 p-3 text-sm font-semibold text-red-700">{message}</p>}<div className="mt-4 max-h-80 space-y-2 overflow-y-auto">{tickets.slice(0, 50).map((ticket) => <div key={ticket.id} className="grid gap-2 rounded-xl border border-slate-200 bg-white p-3 md:grid-cols-[1fr_220px_190px]"><div className="min-w-0"><p className="truncate font-bold">{ticket.titulo}</p><p className="text-xs text-slate-500">{ticket.id} · {ticket.cadena}</p></div><select aria-label={`Asignar ${ticket.id}`} disabled={saving === ticket.id} value={analysts.find((analyst) => analyst.nombre === ticket.asignadoA)?.id ?? ""} onChange={(event) => update(ticket.id, { assignedToId: event.target.value || null })} className="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">Sin asignar</option>{analysts.filter((analyst) => analyst.activo).map((analyst) => <option key={analyst.id} value={analyst.id}>{analyst.nombre}</option>)}</select><select aria-label={`Estado de ${ticket.id}`} disabled={saving === ticket.id} value={ticket.estado} onChange={(event) => update(ticket.id, { status: event.target.value as TicketStatus })} className="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="pendiente">Pendiente</option><option value="seguimiento">Seguimiento</option><option value="espera_cliente">Espera cliente</option><option value="cerrado">Cerrado</option></select></div>)}</div></section>;
}
